In [1]:
# Prepare dataset for environment
%pip install ucimlrepo
%pip install kneed
%pip install plotly

# Import packages to be used
from ucimlrepo import fetch_ucirepo 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# import plotly.graph_objects as go
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

Requirement already satisfied: ucimlrepo in c:\users\anher\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\anher\anaconda3\lib\site-packages (from ucimlrepo) (1.3.4)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\anher\anaconda3\lib\site-packages (from ucimlrepo) (2021.10.8)
Requirement already satisfied: pytz>=2017.3 in c:\users\anher\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\anher\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\anher\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\anher\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.0.0->ucimlrepo) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: kneed in c:\users\anher\anaconda3\lib\site-packages (0.8.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: scipy>=1.0.0 in c:\users\anher\anaconda3\lib\site-packages (from kneed) (1.7.1)
Requirement already satisfied: numpy>=1.14.2 in c:\users\anher\anaconda3\lib\site-packages (from kneed) (1.20.3)
Requirement already satisfied: plotly in c:\users\anher\anaconda3\lib\site-packages (6.7.0)
Requirement already satisfied: packaging in c:\users\anher\anaconda3\lib\site-packages (from plotly) (21.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\anher\anaconda3\lib\site-packages (from plotly) (2.20.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\anher\anaconda3\lib\site-packages (from packaging->plotly) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
######## Power Consumption Dataset ##########
# Multivariate, Classification, Clustering

# Fetch the dataset 
diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296) 
  
# data (as pandas dataframes) 
x = diabetes_130_us_hospitals_for_years_1999_2008.data.features 
y = diabetes_130_us_hospitals_for_years_1999_2008.data.targets

# metadata 
# print(diabetes_130_us_hospitals_for_years_1999_2008.metadata) 
  
# variable information 
# print(diabetes_130_us_hospitals_for_years_1999_2008.variables) 

# Set data as pandas dataframe 
df = x.join(y)
# print(df)

# Algorithms: k-means clustering, Principal component analysis
# Goal is to determine the early readmission of the patient within  30 days of discharge.

C:\Users\anher\AppData\Local\Temp/ipykernel_16908/954731602.py:5: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      99493 non-null   object
 1   gender                    101766 non-null  object
 2   age                       101766 non-null  object
 3   weight                    3197 non-null    object
 4   admission_type_id         101766 non-null  int64
 5   discharge_disposition_id  101766 non-null  int64
 6   admission_source_id       101766 non-null  int64
 7   time_in_hospital          101766 non-null  int64
 8   payer_code                61510 non-null   object
 9   medical_specialty         51817 non-null   object
 10  num_lab_procedures        101766 non-null  int64
 11  num_procedures            101766 non-null  int64
 12  num_medications           101766 non-null  int64
 13  number_outpatient         101766 non-null  int64
 14  number_emergency          101766 non-null  int64
 15  number_inpatient          101766 non-null  int64
 16  diag_1                    101745 non-null  object
 17  diag_2                    101408 non-null  object
 18  diag_3                    100343 non-null  object
 19  number_diagnoses          101766 non-null  int64
 20  max_glu_serum             101766 non-null  object
 21  A1Cresult                 101766 non-null  object
 22  metformin                 101766 non-null  object
 23  repaglinide               101766 non-null  object
 24  nateglinide               101766 non-null  object
 25  chlorpropamide            101766 non-null  object
 26  glimepiride               101766 non-null  object
 27  acetohexamide             101766 non-null  object
 28  glipizide                 101766 non-null  object
 29  glyburide                 101766 non-null  object
 30  tolbutamide               101766 non-null  object
 31  pioglitazone              101766 non-null  object
 32  rosiglitazone             101766 non-null  object
 33  acarbose                  101766 non-null  object
 34  miglitol                  101766 non-null  object
 35  troglitazone              101766 non-null  object
 36  tolazamide                101766 non-null  object
 37  examide                   101766 non-null  object
 38  citoglipton               101766 non-null  object
 39  insulin                   101766 non-null  object
 40  glyburide-metformin       101766 non-null  object
 41  glipizide-metformin       101766 non-null  object
 42  glimepiride-pioglitazone  101766 non-null  object
 43  metformin-rosiglitazone   101766 non-null  object
 44  metformin-pioglitazone    101766 non-null  object
 45  change                    101766 non-null  object
 46  diabetesMed               101766 non-null  object
 47  readmitted                101766 non-null  object
dtypes: int64(11), object(37)
memory usage: 37.3+ MB

In [4]:
print(df[df.isna().any(axis=1)])

                   race  gender      age weight  admission_type_id  \
0             Caucasian  Female   [0-10)    NaN                  6
1             Caucasian  Female  [10-20)    NaN                  1
2       AfricanAmerican  Female  [20-30)    NaN                  1
3             Caucasian    Male  [30-40)    NaN                  1
4             Caucasian    Male  [40-50)    NaN                  1
...                 ...     ...      ...    ...                ...
101761  AfricanAmerican    Male  [70-80)    NaN                  1
101762  AfricanAmerican  Female  [80-90)    NaN                  1
101763        Caucasian    Male  [70-80)    NaN                  1
101764        Caucasian  Female  [80-90)    NaN                  2
101765        Caucasian    Male  [70-80)    NaN                  1

        discharge_disposition_id  admission_source_id  time_in_hospital  \
0                             25                    1                 1
1                              1                    7                 3
2                              1                    7                 2
3                              1                    7                 2
4                              1                    7                 1
...                          ...                  ...               ...
101761                         3                    7                 3
101762                         4                    5                 5
101763                         1                    7                 1
101764                         3                    7                10
101765                         1                    7                 6

       payer_code         medical_specialty  ...  citoglipton  insulin  \
0             NaN  Pediatrics-Endocrinology  ...           No       No
1             NaN                       NaN  ...           No       Up
2             NaN                       NaN  ...           No       No
3             NaN                       NaN  ...           No       Up
4             NaN                       NaN  ...           No   Steady
...           ...                       ...  ...          ...      ...
101761         MC                       NaN  ...           No     Down
101762         MC                       NaN  ...           No   Steady
101763         MC                       NaN  ...           No     Down
101764         MC           Surgery-General  ...           No       Up
101765        NaN                       NaN  ...           No       No

        glyburide-metformin  glipizide-metformin  glimepiride-pioglitazone  \
0                        No                   No                        No
1                        No                   No                        No
2                        No                   No                        No
3                        No                   No                        No
4                        No                   No                        No
...                     ...                  ...                       ...
101761                   No                   No                        No
101762                   No                   No                        No
101763                   No                   No                        No
101764                   No                   No                        No
101765                   No                   No                        No

        metformin-rosiglitazone metformin-pioglitazone change diabetesMed  \
0                            No                     No     No          No
1                            No                     No     Ch         Yes
2                            No                     No     No         Yes
3                            No                     No     Ch         Yes
4                            No                     No     Ch         Yes
...                         ...                    ...    ...         ...
101761                       No                     No     Ch         Yes
101762                       No                     No     No         Yes
101763                       No                     No     Ch         Yes
101764                       No                     No     Ch         Yes
101765                       No                     No     No          No

        readmitted
0               NO
1              >30
2               NO
3               NO
4               NO
...            ...
101761         >30
101762          NO
101763          NO
101764          NO
101765          NO

[100723 rows x 48 columns]

In [5]:
##### Data Cleaning ###### 
# Check Data types
# df.info()

### Check for missing values ###
naCheck = df.isna().any().any()
print(naCheck)

# print("This is naCheck1")
# naCheck1 = df.isna().any()
# print(naCheck1)


# print("This is naCheck3")
# naCheck3 = df.isna().any(axis=None)
# print(naCheck3)

print("This gives the number of NA values for each column")
naCheck4 = df.isna().sum()
print(naCheck4)

# naCheck2 = np.any(np.isnan(df)) # This is an iterable that uses even the column headers.
# np.isinf(df).any().any()
# np.any(np.isnan(df))
# print(naCheck2)

# Found missing values
if naCheck == True:
    replacements = {'cola': 0, 'colb': 'Other'}
    dfChecked = df.fillna(replacements)
    print(dfChecked)

True
This gives the number of NA values for each column
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64
                   race  gender      age weight  admission_type_id  \
0             Caucasian  Female   [0-10)    NaN                  6
1             Caucasian  Female  [10-20)    NaN                  1
2       AfricanAmerican  Female  [20-30)    NaN                  1
3             Caucasian    Male  [30-40)    NaN                  1
4             Caucasian    Male  [40-50)    NaN                  1
...                 ...     ...      ...    ...                ...
101761  AfricanAmerican    Male  [70-80)    NaN                  1
101762  AfricanAmerican  Female  [80-90)    NaN                  1
101763        Caucasian    Male  [70-80)    NaN                  1
101764        Caucasian  Female  [80-90)    NaN                  2
101765        Caucasian    Male  [70-80)    NaN                  1

        discharge_disposition_id  admission_source_id  time_in_hospital  \
0                             25                    1                 1
1                              1                    7                 3
2                              1                    7                 2
3                              1                    7                 2
4                              1                    7                 1
...                          ...                  ...               ...
101761                         3                    7                 3
101762                         4                    5                 5
101763                         1                    7                 1
101764                         3                    7                10
101765                         1                    7                 6

       payer_code         medical_specialty  ...  citoglipton  insulin  \
0             NaN  Pediatrics-Endocrinology  ...           No       No
1             NaN                       NaN  ...           No       Up
2             NaN                       NaN  ...           No       No
3             NaN                       NaN  ...           No       Up
4             NaN                       NaN  ...           No   Steady
...           ...                       ...  ...          ...      ...
101761         MC                       NaN  ...           No     Down
101762         MC                       NaN  ...           No   Steady
101763         MC                       NaN  ...           No     Down
101764         MC           Surgery-General  ...           No       Up
101765        NaN                       NaN  ...           No       No

        glyburide-metformin  glipizide-metformin  glimepiride-pioglitazone  \
0                        No                   No                        No
1                        No                   No                        No
2                        No                   No                        No
3                        No                   No                        No
4                        No                   No                        No
...                     ...                  ...                       ...
101761                   No                   No                        No
101762                   No                   No                        No
101763                   No                   No                        No
101764                   No                   No                        No
101765                   No                   No                        No

        metformin-rosiglitazone metformin-pioglitazone change diabetesMed  \
0                            No                     No     No          No
1                            No                     No     Ch         Yes
2                            No                     No     No         Yes
3                            No                     No     Ch         Yes
4                            No                     No     Ch         Yes
...                         ...                    ...    ...         ...
101761                       No                     No     Ch         Yes
101762                       No                     No     No         Yes
101763                       No                     No     Ch         Yes
101764                       No                     No     Ch         Yes
101765                       No                     No     No          No

        readmitted
0               NO
1              >30
2               NO
3               NO
4               NO
...            ...
101761         >30
101762          NO
101763          NO
101764          NO
101765          NO

[101766 rows x 48 columns]

In [6]:
######## Missing Value Handling ########

datatypes = {'race': 'object', 'weight': 'object', 'payer_code': 'object', 'medical_specialty': 'object', 'diag_1': 'object', 'diag_2': 'object', 'diag_3': 'object'}
replaceType = {'object': 'Other', 'int64': 0 }
toReplace = {'race': 'Other', 'weight': 'Other', 'payer_code': 'Other', 'medical_specialty': 'Other', 'diag_1': 'Other', 'diag_2': 'Other', 'diag_3': 'Other'}

cols_with_missing = df.columns[df.isna().any()].tolist()
type(cols_with_missing[0])


dfChecked = dfChecked.fillna(toReplace)
# for i in cols_with_missing:
    # name = str(cols_with_missing[i])
    # df.loc[:,cols_with_missing[i]].fillna(replaceType.get(cols_with_missing[i]))
    #df.loc[:,cols_with_missing[i]].fillna(replaceType.get(datatypes.get(cols_with_missing[i])))
    #df.loc[:,cols_with_missing[i]].fillna(toReplace)
# print(cols_with_missing[0])
# df.loc[:,cols_with_missing[0]]
# print(replaceType.get(datatypes.get('race')))

In [7]:
# Recheck the data 
dfChecked.isna().sum()

race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [8]:
# dfChecked.value_counts().plot(x='race', y='readmitted', kind='bar')
# plt.show()

In [9]:
dfFreq = dfChecked.value_counts(['race', 'readmitted']).reset_index().rename(columns={0:'frequency'})
dfFreq

               race readmitted  frequency
0         Caucasian         NO      40383
1         Caucasian        >30      27124
2   AfricanAmerican         NO      10421
3         Caucasian        <30       8592
4   AfricanAmerican        >30       6634
5             Other         NO       2462
6   AfricanAmerican        <30       2155
7          Hispanic         NO       1183
8             Other        >30        984
9          Hispanic        >30        642
10            Asian         NO        415
11            Other        <30        333
12         Hispanic        <30        212
13            Asian        >30        161
14            Asian        <30         65

In [10]:
fig = px.bar(dfFreq, x="race", y="frequency", color="readmitted", title="Frequency vs race", barmode='group')
fig.show()

In [11]:
dfFreq = dfChecked.value_counts(['gender', 'readmitted']).reset_index().rename(columns={0:'frequency'})
dfFreq
fig = px.bar(dfFreq, x="gender", y="frequency", color="readmitted", title="Frequency vs gender", barmode='group')
fig.show()

In [12]:
x = dfChecked.melt().value_counts().reset_index().rename(columns={0:'freq'})
print(x.sort_values(by='variable'))

       variable      value   freq
81    A1Cresult         >8   8216
25    A1Cresult       None  84748
125   A1Cresult         >7   3812
110   A1Cresult       Norm   4990
1600   acarbose         Up     10
...         ...        ...    ...
295      weight    [50-75)    897
246      weight   [75-100)   1336
758      weight    [25-50)     97
1571     weight  [175-200)     11
349      weight  [100-125)    625

[2835 rows x 3 columns]

In [13]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows = 16, cols = 3, 
    subplot_titles = ('race', 'gender', 'age','weight','admission_type_id','discharge_disposition_id','admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed')
)

In [14]:
# x1 = dfChecked.melt(var_name='category',value_name='freq')
# dfFreqTables = x1.sort_values(by='category')
# # print(dfFreqTables)

# fig = px.bar(dfFreqTables, x = 'category', y = 'freq',
#              facet_col= 'category', 
#              facet_col_wrap=3, facet_row_spacing= 0.06,
#              title = 'FreqTable plots')

# fig.update_yaxes(matches=None)
# fig.update_layout(height=4000, width= 800)
# fig.show()

In [15]:
i = 1
j = 1
d = {}
fig.update_layout(height=4000, width= 800, title_text = "PLOTS")
for col in dfChecked.columns: 
    if col == 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        # d['fig{0}'.format(col)]  = px.bar(dfFreq, x=col, y="frequency", color="readmitted", barmode='group')
        fig.add_trace(go.Bar(x=dfFreq[col], y=dfFreq['frequency'], legendgroup='readmitted', alignmentgroup='readmitted', name='readmitted', showlegend=True), i, j)
    if col != 'readmitted' and col != 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        # d['fig{0}'.format(col)]  = px.bar(dfFreq, x=col, y="frequency", color="readmitted", barmode='group')
        fig.add_trace(go.Bar(x=dfFreq[col], y=dfFreq['frequency'], legendgroup='readmitted', alignmentgroup='readmitted', name='readmitted', showlegend=False), i, j)
    if j <= 4:
        j += 1
    if j == 4:
        i += 1
        j = 1 



# fig.update_layout(height=4000, width= 800,
#                   title_text = "PLOTS", barmode= 'group')
# fig.update_layout(barmode='group')

fig.show()

In [16]:
fig.update_layout(height=4000, width= 1200, title_text = "PLOTS")
fig.show()

In [17]:
fig.update_layout(barmode='group', bargroupgap = .1, bargap = 0.5)
fig.show()

In [18]:
fig = make_subplots(rows = 16, cols = 3, 
    subplot_titles = ('race', 'gender', 'age','weight','admission_type_id','discharge_disposition_id','admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed')
)

i = 1
j = 1
d = {}

names = set()
fig.for_each_trace(
    lambda trace:
        trace.update(showlegend=False)
        if (trace.name in names) else names.add(trace.name))

fig.update_layout(height=4000, width= 800, title_text = "PLOTS")
for col in dfChecked.columns: 
    if col == 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        figPx = px.bar(dfFreq, x=dfFreq[col], y=dfFreq['frequency'], color="readmitted", barmode='group')
        #fig.add_trace(figPx.data[0], i, j)
        bar_trace = figPx.data[0]
        bar_trace1 = figPx.data[1]
        bar_trace2 = figPx.data[2]

        fig.add_trace(bar_trace, i, j)
        fig.add_trace(bar_trace1, i, j)
        fig.add_trace(bar_trace2, i, j)
    if col != 'readmitted' and col != 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        figPx = px.bar(dfFreq, x=dfFreq[col], y=dfFreq['frequency'], color="readmitted", barmode='group')
        # fig.add_trace(figPx.data[0], i, j)
        bar_trace = figPx.data[0]
        bar_trace1 = figPx.data[1]
        bar_trace2 = figPx.data[2]

        fig.add_trace(bar_trace, i, j)
        fig.add_trace(bar_trace1, i, j)
        fig.add_trace(bar_trace2, i, j)
    if j <= 4:
        j += 1
    if j == 4:
        i += 1
        j = 1 

names = set()
fig.for_each_trace(
    lambda trace:
        trace.update(showlegend=False)
        if (trace.name in names) else names.add(trace.name))

fig.show()

In [ ]:
fig = make_subplots(rows=1, cols=2)
dfFreq = dfChecked.value_counts(['race', 'readmitted']).reset_index().rename(columns={0:'frequency'})
figPx = px.bar(dfFreq, x=dfFreq['race'], y=dfFreq['frequency'], color='readmitted', barmode='group')
# type(figPx)

bar_trace = figPx.data[0]
bar_trace1 = figPx.data[1]
bar_trace2 = figPx.data[2]

fig.add_trace(bar_trace)
fig.add_trace(bar_trace1)
fig.add_trace(bar_trace2)
fig.show()
# To clear figure
fig.data = []

In [20]:
# x1 = dfChecked.melt(var_name='category',value_name='freq')
# dfFreqTables = x1.sort_values(by='category')
# fig = px.bar(dfFreqTables, x = 'category', y='freq',
#              facet_col='category', facet_col_wrap=4,
#              title="PLOTS")
# fig.update_yaxes(matches=None)
# fig.show()

In [21]:
# for trace in d['figrace'].data:
#     fig.add_trace(trace, row = 1,col = 1)
# for trace in d['figgender'].data:
#     fig.add_trace(trace, row = 1,col = 2)
# for trace in d['figage'].data:
#     fig.add_trace(trace, row = 1,col = 3)

# i = 1
# j = 1
# for key in d:
#     for trace in d[key].data:
#         fig.add_trace(trace, i, j)
#     if j <= 4:
#         j += 1
#     if j == 4:
#         i += 1
#         j = 1 
# fig.show()

In [22]:
# How to graph the 47 columns in dfChecked against readmitted?
# Identify your target x-axis column
# target_col = 'readmitted'

# Loop through all other columns
# for col in dfChecked.columns:
#     if col != target_col:
#         dfChecked.value_counts().plot(x=col, y=target_col, kind='bar')
#         plt.show()

In [23]:
# print(list(dfChecked))
dfCheckedFeaturesNames = list(dfChecked.drop(columns='readmitted'))
print(dfCheckedFeaturesNames)

['race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']

In [24]:
dfChecked['readmitted'].value_counts(ascending=False)

NO     54864
>30    35545
<30    11357
Name: readmitted, dtype: int64

In [25]:
dfChecked1 = dfChecked['readmitted'].replace('NO', 0, inplace=True)

In [28]:
dfFreqTables =  dfChecked.melt(var_name='category',value_name='freq')
dfFreqTotal = dfFreqTables.sort_values(by='category')
print(dfFreqTotal)

          category   freq
2238850  A1Cresult   None
2171001  A1Cresult     >8
2171002  A1Cresult     >8
2171003  A1Cresult   None
2171004  A1Cresult   None
...            ...    ...
373145      weight  Other
373146      weight  Other
373147      weight  Other
373149      weight  Other
407062      weight  Other

[4884768 rows x 2 columns]

In [31]:
dfCountTotal = dfFreqTotal.value_counts().reset_index().rename(columns={0:'count'})
dfCountTotal

                      category freq   count
0                      examide   No  101766
1                  citoglipton   No  101766
2     glimepiride-pioglitazone   No  101765
3       metformin-pioglitazone   No  101765
4                acetohexamide   No  101765
...                        ...  ...     ...
2830                    diag_3  484       1
2831                    diag_3  485       1
2832                    diag_1  870       1
2833                    diag_3   49       1
2834                    diag_3  871       1

[2835 rows x 3 columns]

In [36]:
dfChecked

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),Other,6,25,1,1,Other,Pediatrics-Endocrinology,...,No,No,No,No,No,No,No,No,No,0
1,Caucasian,Female,[10-20),Other,1,1,7,3,Other,Other,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),Other,1,1,7,2,Other,Other,...,No,No,No,No,No,No,No,No,Yes,0
3,Caucasian,Male,[30-40),Other,1,1,7,2,Other,Other,...,No,Up,No,No,No,No,No,Ch,Yes,0
4,Caucasian,Male,[40-50),Other,1,1,7,1,Other,Other,...,No,Steady,No,No,No,No,No,Ch,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,AfricanAmerican,Male,[70-80),Other,1,3,7,3,MC,Other,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,AfricanAmerican,Female,[80-90),Other,1,4,5,5,MC,Other,...,No,Steady,No,No,No,No,No,No,Yes,0
101763,Caucasian,Male,[70-80),Other,1,1,7,1,MC,Other,...,No,Down,No,No,No,No,No,Ch,Yes,0
101764,Caucasian,Female,[80-90),Other,2,3,7,10,MC,Surgery-General,...,No,Up,No,No,No,No,No,Ch,Yes,0
101765,Caucasian,Male,[70-80),Other,1,1,7,6,Other,Other,...,No,No,No,No,No,No,No,No,No,0

In [42]:
# fig = px.sunburst(dfChecked, path= dfCheckedFeaturesNames,
                 #  values='readmitted',
                #   color='readmitted',
                #   color_continuous_scale='rdbu_r',
                #   width=960, height=600
 #                )

i = 1
j = 1
d = {}

for col in dfChecked.columns: 
    if col == 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        # d['fig{0}'.format(col)]  = px.bar(dfFreq, x=col, y="frequency", color="readmitted", barmode='group')
        # fig.add_trace(go.Bar(x=dfFreq[col], y=dfFreq['frequency'], legendgroup='readmitted', alignmentgroup='readmitted', name='readmitted', showlegend=True), i, j)
        figPx = px.sunburst(dfFreq, path = [col, 'readmitted'], values=dfFreq['frequency'])
        #fig.add_trace(figPx.data[0], i, j)
        bar_trace = figPx.data[0]

        fig.add_trace(bar_trace)

    if col != 'readmitted' and col != 'race':
        dfFreq = dfChecked.value_counts([col, 'readmitted']).reset_index().rename(columns={0:'frequency'})
        # d['fig{0}'.format(col)]  = px.bar(dfFreq, x=col, y="frequency", color="readmitted", barmode='group')
        # fig.add_trace(go.Bar(x=dfFreq[col], y=dfFreq['frequency'], legendgroup='readmitted', alignmentgroup='readmitted', name='readmitted', showlegend=False), i, j)
        figPx = px.sunburst(dfFreq, path = [col, 'readmitted'], values=dfFreq['frequency'])
        #fig.add_trace(figPx.data[0], i, j)
        bar_trace = figPx.data[0]

        fig.add_trace(bar_trace)
    if j <= 4:
        j += 1
    if j == 4:
        i += 1
        j = 1 



# fig.update_layout(height=4000, width= 800,
#                   title_text = "PLOTS", barmode= 'group')
# fig.update_layout(barmode='group')

fig.show()



fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.show()